
= asciiDoc, .adoc, my new favorite text markup.

* asciiDoc, .adoc, is pretty old too, but i just learned about it.
** simpler syntax, like MD, but still extensible.
** use = as header rather than #, so solve my #1 gripe about .md
** may become my new favorite!
** https://asciidoc.org
** .adoc  does not have good support for bullet that span multiple paragraph.  but maybe use sub bullets


== 101

adoc is a bit picky about space, not indentation, but space delimiter about token it need to parse. +
a space and plus at the end of the line is a line break. +
another empty line is paragraph break.  

i think i can live with this kind of setup

leading dot might be some command thing as well

maybe what i really care is for vim to have some color in the text file to call attention.
rendering to web site will likely be forced by use of .md  in much collaboration and rendering engine.


== 102

*bold*
_italic_

[red]#colored text#

passthru, ie escaped
+++*bold*+++

ie use triple plus sign before and after for verbatim text without asciiDoc parser interpreting it.

but can have
_+++*bold**+++_ 

since _ _ for italic is outside the triple plus, the italic text stands.

URL link is also decent.  https://photos.app.goo.gl/cAngzDKubfNcsBLu7[gFoto on adoc].




== 103

* https://gist.asciidoctor.org




