 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" acopia.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" admin.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" aix_cd_catalog.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" aix.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" apple.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" aws.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" backup.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" bigdata.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" bios.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" cfengine.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" config_mgmt_comparison.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" coreos.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" db2.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" development.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" devops.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" docker.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" docPlatform.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" dos.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" emcCelerra.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" emc.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" ent_prod.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" factory_pw.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" firewall.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" flexlm.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" fs.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" funny404.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" fusionio.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" general_unix.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" hpux.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" hpux.supl.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" index.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" index.old.20110819.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" infiniband.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" ipmi.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" ipv6.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" irix.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" javascript.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" k8s.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" ldap.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" learn.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" legato.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" lustre.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" megaraid.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" monitor.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" mpi.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" mrf.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" mysql.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" netapp.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" netArch.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" net.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" nixos.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" openstack.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" oracle.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" perl.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" postfix.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" postgres.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" psg0.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" psg1.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" psg2.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" psg2-template.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" psg.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" psg-orig.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" puppet.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" python.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" R.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" sci-app.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" sci-file.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" scriptRosetta.word.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" singularity.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" softenv+modules.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" sol.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" sqlite.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" ssh.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" template.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" template-psg2style.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" termSvr.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" test.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" tool.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" vagrant.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" veritas.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" vi.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" vm.html
 sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" vnc.html
 #sed -i "s^psg.ask-margo.com/^tin6150.github.io/psg/^g" wiki.html
