 sed -i "s/php.html/php.txt/" aws.html
 sed -i "s/php.html/php.txt/" bigdata.html
 sed -i "s/php.html/php.txt/" cfengine.html
 sed -i "s/php.html/php.txt/" coreos.html
 sed -i "s/php.html/php.txt/" development.html
 sed -i "s/php.html/php.txt/" docker.html
 sed -i "s/php.html/php.txt/" fusionio.html
 sed -i "s/php.html/php.txt/" index.old.20110819.html
 sed -i "s/php.html/php.txt/" ipv6.html
 sed -i "s/php.html/php.txt/" lustre.html
 sed -i "s/php.html/php.txt/" mrf.html
 sed -i "s/php.html/php.txt/" nixos.html
 sed -i "s/php.html/php.txt/" openstack.html
 sed -i "s/php.html/php.txt/" perl.html
 sed -i "s/php.html/php.txt/" postfix.html
 sed -i "s/php.html/php.txt/" psg1.html
 sed -i "s/php.html/php.txt/" psg2-template.html
 sed -i "s/php.html/php.txt/" psg-orig.html
 sed -i "s/php.html/php.txt/" puppet.html
 sed -i "s/php.html/php.txt/" scriptRosetta.word.html
 sed -i "s/php.html/php.txt/" softenv+modules.html
 sed -i "s/php.html/php.txt/" sourceControl.html
 sed -i "s/php.html/php.txt/" template-psg2style.html
