 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" admin.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" apple.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" backup.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" development.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" docPlatform.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" dos.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" emc.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" ent_prod.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" factory_pw.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" flexlm.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" fs.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" general_unix.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" hpux.supl.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" ipmi.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" irix.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" ldap.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" legato.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" linux.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" monitor.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" mysql.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" netArch.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" perl.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" postgres.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" python.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" sci-app.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" sci-file.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" softenv+modules.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" sol.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" sourceControl.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" sqlite.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" termSvr.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" tool.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" veritas.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" vi.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" vnc.html
 sed -i "s/\"ting\"<\/div>/bofh1<\/div>/" wiki.html
