 sed -i "s/\"ting\"<BR>/sn5050<BR>/" acopia.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" db2.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" emcCelerra.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" infiniband.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" isilon.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" lsf.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" mpi.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" netapp.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" oracle.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" template.html
 sed -i "s/\"ting\"<BR>/sn5050<BR>/" vm.html
