 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" acopia.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" admin.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" aix.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" aix_cd_catalog.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" apple.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" aws.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" backup.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" bigdata.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" cfengine.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" coreos.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" db2.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" development.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" devops.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" docker.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" docPlatform.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" dos.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" emc.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" emcCelerra.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" ent_prod.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" factory_pw.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" flexlm.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" fs.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" fusionio.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" general_unix.beforeBracketConversion.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" general_unix.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" hpux.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" hpux.supl.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" index.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" index.old.20110819.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" infiniband.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" ipmi.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" ipv6.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" irix.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" ldap.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" learn.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" legato.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" linux.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" lsf.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" lustre.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" monitor.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" mpi.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" mrf.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" mysql.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" net.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" netapp.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" netArch.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" netArch-bk20090304.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" nixos.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" openstack.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" oracle.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" perl.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" postfix.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" postgres.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" psg.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" psg1.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" psg2.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" psg2-template.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" psg-orig.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" puppet.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" python.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" R.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" sci-app.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" sci-file.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" scriptRosetta.word.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" softenv+modules.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" sol.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" sqlite.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" template.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" template-psg2style.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" termSvr.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" test.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" tool.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" veritas.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" vi.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" vm.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" vnc.html
 sed -i "s/www.cs.fiu.edu\/~tho01\/psg/psg.ask-margo.com/g" wiki.html
