#### $HOE/.xinitrc is really a bash file
#### tell how to start windows manager, or just run an xterm...
#### full PATH recommended
#### invoked by "startx" ??
#### may not be needed if get lightdm , gdm or any Display Manager running (?)

#/bin/xterm
# startxkde
startxfce4
