 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" bigdata.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" cfengine.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" coreos.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" docker.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" fusionio.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" gdb.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" googleb9770987b6d87217.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" index.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" index_redirect.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" ipv6.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" lustre.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" nixos.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" postfix.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" psg.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" psg2.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" psg2-template.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" puppet.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" redirect.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" template-psg2style.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" -e "s/AUHAUH on the outside, LAPPLAPP on the inside/ting/" tmp.xfer2tool.snip.tmp.html
