 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" acopia.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" admin.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" aix.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" aix_cd_catalog.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" apple.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" aws.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" backup.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" bigdata.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" cfengine.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" coreos.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" db2.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" development.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" docker.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" docPlatform.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" dos.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" emc.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" emcCelerra.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" ent_prod.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" factory_pw.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" flexlm.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" fs.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" fusionio.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" gdb.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" general_unix.beforeBracketConversion.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" general_unix.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" googleb9770987b6d87217.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" hpux.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" hpux.supl.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" index.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" index.old.20110819.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" index_redirect.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" infiniband.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" ipmi.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" ipv6.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" irix.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" isilon.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" ldap.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" learn.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" legato.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" linux.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" lsf.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" lustre.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" monitor.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" mpi.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" mrf.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" mysql.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" net.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" netapp.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" netArch.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" netArch-bk20090304.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" nixos.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" oracle.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" perl.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" postfix.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" postgres.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" psg.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" psg1.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" psg2.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" psg2-template.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" psg-orig.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" puppet.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" python.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" R.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" redirect.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" sci-app.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" sci-file.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" scriptRosetta.ABANDONE.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" scriptRosetta.ABANDONE.text.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" scriptRosetta.word.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" softenv+modules.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" sol.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" sourceControl.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" sqlite.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" template.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" template-psg2style.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" termSvr.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" test.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" tmp.xfer2tool.snip.tmp.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" tool.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" veritas.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" vi.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" vm.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" vnc.html
 sed -i -e "s/LYS on the outside, LKS in the inside/ting/" wiki.html
