 ## fgrep -l "www.grumpyxmas.com" *html  | awk '{print " sed -i \"s/www.grumpyxmas.com/dl.dropboxusercontent.com\\\/u\\\/31360775\\\/psg/\" " $0 }'  > run5a_grumpy.sh
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" aws.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" bigdata.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" cfengine.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" coreos.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" docker.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" emc.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" emcCelerra.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" fusionio.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" index.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" index.old.20110819.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" ipmi.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" ipv6.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" isilon.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" ldap.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" lustre.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" mysql.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" netapp.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" netArch.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" netArch-bk20090304.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" nixos.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" postfix.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" postgres.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" psg.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" psg1.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" psg2.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" psg2-template.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" psg-orig.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" puppet.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" scriptRosetta.ABANDONE.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" scriptRosetta.ABANDONE.text.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" scriptRosetta.word.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" sqlite.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" template-psg2style.html
 sed -i "s/www.grumpyxmas.com/dl.dropboxusercontent.com\/u\/31360775\/psg/" veritas.html
