 ## fgrep -L "www.grumpyxmas.com" *html  | awk '{print " sed -i \"s/www.grumpyxmas.com/psg.skinforum.org/\" " $0 }'  > run5_grumpy.sh
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" acopia.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" admin.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" aix.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" aix_cd_catalog.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" apple.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" backup.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" db2.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" development.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" docPlatform.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" dos.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" ent_prod.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" factory_pw.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" flexlm.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" fs.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" gdb.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" general_unix.beforeBracketConversion.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" general_unix.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" googleb9770987b6d87217.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" hpux.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" hpux.supl.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" index_redirect.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" infiniband.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" irix.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" learn.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" legato.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" linux.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" lsf.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" monitor.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" mpi.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" mrf.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" net.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" oracle.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" perl.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" python.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" R.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" redirect.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" sci-app.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" sci-file.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" softenv+modules.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" sol.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" sourceControl.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" template.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" termSvr.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" test.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" tmp.xfer2tool.snip.tmp.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" tool.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" vi.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" vm.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" vnc.html
 sed -i "s/www.grumpyxmas.com/psg.skinforum.org/" wiki.html
